blank_issues_enabled: true
contact_links:
    - name: Questions & Discussions
      url: https://github.com/ghettovoice/abnf/discussions
      about: Use GitHub Discussions for questions and general discussion
